In [4]:
%load_ext autoreload
%autoreload 2

In [3]:
import torch
import torch_geometric as pyg
import torch_geometric.datasets as pygd
import warnings
from sklearn.exceptions import UndefinedMetricWarning

warnings.filterwarnings("ignore", category=UndefinedMetricWarning)

In [6]:
from gpn.experiments.multiple_run_experiment import MultipleRunExperiment
from gpn.experiments.transductive_experiment import TransductiveExperiment
from gpn.utils.config import (
    DataConfiguration,
    ModelConfiguration,
    RunConfiguration,
    TrainingConfiguration,
)


def create_experiment(model_name):
    run_cfg = RunConfiguration(
        job="train",
        eval_mode="default",
        experiment_directory="./.cache",
        save_model=True,
        gpu=0,
        experiment_name="ood_loc",
        num_inits=1,
        num_splits=1,
    )
    data_cfg = DataConfiguration(
        dataset="CiteSeer",
        split_no=1,
        root="./data",
        ood_flag=True,
        train_samples_per_class=0.05,
        val_samples_per_class=0.15,
        test_samples_per_class=0.8,
        split="random",
        ood_setting="poisoning",
        ood_type="leave_out_classes",
        ood_num_left_out_classes=-1,
        ood_leave_out_last_classes=True,
    )

    model_cfg = ModelConfiguration(
        model_name=model_name,
        seed=42,
        init_no=1,
        dim_hidden=64,
        dropout_prob=0.5,
        K=10,
        add_self_loops=True,
        maf_layers=0,
        gaussian_layers=0,
        use_batched_flow=True,
        loss_reduction="sum",
        approximate_reg=True,
        flow_weight_decay=0.0,
        pre_train_mode="flow",
        alpha_evidence_scale="latent-new",
        alpha_teleport=0.1,
        entropy_reg=0.0001,
        dim_latent=16,
        radial_layers=10,
        sparse_propagation=True,
        sparse_x_prune_threshold=0.01
    )

    train_cfg = TrainingConfiguration(
        epochs=100000,
        stopping_mode="default",
        stopping_patience=50,
        stopping_restore_best=True,
        stopping_metric="val_CE",
        stopping_minimize=True,
        finetune_epochs=0,
        warmup_epochs=5,
        lr=0.01,
        weight_decay=0.001,
    )

    return MultipleRunExperiment(run_cfg, data_cfg, model_cfg, train_cfg)


# gpn_e = create_experiment("GPN")
lop_e = create_experiment("GPN_LOP")
res_lop = lop_e.run()
# res = gpn_e.run()
res_lop

AssertionError: 

In [ ]:
import pandas as pd
from gpn.utils.utils import results_dict_to_df

df_lop = results_dict_to_df(res_lop)
df = results_dict_to_df(res)

pd.set_option("display.max_rows", None)
(pd.DataFrame(
    dict(
        val_gpn=df["val"],
        test_gpn=df["test"],
        val_lop=df_lop["val"],
        test_lop=df_lop["test"],
    )
)).round(4).dropna()

In [ ]:
from gpn.data.dataset_manager import DatasetManager
from gpn.data.dataset_provider import InMemoryDatasetProvider
import torch_sparse as ts

ds = InMemoryDatasetProvider(
    DatasetManager(
        dataset="AmazonPhotos",
        split_no=1,
        root="./data",
        ood_flag=True,
        train_samples_per_class=0.05,
        val_samples_per_class=0.15,
        test_samples_per_class=0.8,
        split="random",
        ood_setting="poisoning",
        ood_type="leave_out_classes",
        ood_num_left_out_classes=-1,
        ood_leave_out_last_classes=True,
    )
).to_sparse()

batch = list(ds.loader())[0]

batch.adj_t.dtype()

In [ ]:
N = batch.x.shape[0]
adj_t = batch.adj_t.cuda()
adj_t

In [5]:
import torch_sparse as ts

adj_t = ts.SparseTensor.from_dense(
    torch.Tensor([[0, 1, 0], [1, 0, 1], [0, 1, 0]])
).cuda()
x = torch.Tensor([1, 10, 100]).view(-1, 1).cuda()
N = x.shape[0]
adj_t /= x
print(adj_t.dtype())
adj_t.set_diag(torch.tensor([6,2,3], dtype=torch.float32).cuda()).to_dense()

torch.float32


tensor([[6.0000, 1.0000, 0.0000],
        [0.1000, 2.0000, 0.1000],
        [0.0000, 0.0100, 3.0000]], device='cuda:0')

In [19]:
from gpn.layers.appnp_propagation import APPNPPropagation

prop = APPNPPropagation(1, 0, 0, normalization="sym")
x = ts.SparseTensor.eye(N, dtype=torch.float32, device="cuda")  # type: ignore

p: ts.SparseTensor = prop(x, adj_t)

p.to_dense()

tensor([[0.5000, 0.6455, 0.0000],
        [0.0645, 0.8333, 0.0908],
        [0.0000, 0.0091, 0.9901]], device='cuda:0')

In [20]:
prop = APPNPPropagation(1, 0, 0, normalization="sym")
x = torch.diag(torch.ones(N, device="cuda"))

p: ts.SparseTensor = prop(x, adj_t)

p

tensor([[0.5000, 0.6455, 0.0000],
        [0.0645, 0.8333, 0.0908],
        [0.0000, 0.0091, 0.9901]], device='cuda:0')

In [ ]:
ts.SparseTensor.from_edge_index(torch.tensor([[0,1],[0,1]]),sparse_sizes=(10,3)).dtype()

In [43]:
ts.SparseTensor.from_.get_diag()

TypeError: <lambda>() missing 1 required positional argument: 'self'