In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import torch_geometric as pyg
import torch_geometric.datasets as pygd
import warnings
from sklearn.exceptions import UndefinedMetricWarning

warnings.filterwarnings("ignore", category=UndefinedMetricWarning)

In [84]:
from gpn.experiments.multiple_run_experiment import MultipleRunExperiment
from gpn.experiments.transductive_experiment import TransductiveExperiment
from gpn.utils.config import (
    DataConfiguration,
    ModelConfiguration,
    RunConfiguration,
    TrainingConfiguration,
)


def create_experiment(model_name):
    run_cfg = RunConfiguration(
        job="train",
        eval_mode="default",
        experiment_directory="./.cache",
        save_model=True,
        gpu=0,
        experiment_name="ood_loc",
        num_inits=1,
        num_splits=1,
    )
    data_cfg = DataConfiguration(
        dataset="AmazonPhotos",
        split_no=1,
        root="./data",
        ood_flag=True,
        train_samples_per_class=0.05,
        val_samples_per_class=0.15,
        test_samples_per_class=0.8,
        split="random",
        ood_setting="poisoning",
        ood_type="leave_out_classes",
        ood_num_left_out_classes=-1,
        ood_leave_out_last_classes=True,
    )

    model_cfg = ModelConfiguration(
        model_name=model_name,
        seed=42,
        init_no=1,
        dim_hidden=64,
        dropout_prob=0.5,
        K=10,
        add_self_loops=True,
        maf_layers=0,
        gaussian_layers=0,
        use_batched_flow=True,
        loss_reduction="sum",
        approximate_reg=True,
        flow_weight_decay=0.0,
        pre_train_mode="flow",
        alpha_evidence_scale="latent-new",
        alpha_teleport=0.1,
        entropy_reg=0.0001,
        dim_latent=16,
        radial_layers=10,
    )

    train_cfg = TrainingConfiguration(
        epochs=100000,
        stopping_mode="default",
        stopping_patience=50,
        stopping_restore_best=True,
        stopping_metric="val_CE",
        stopping_minimize=True,
        finetune_epochs=0,
        warmup_epochs=5,
        lr=0.01,
        weight_decay=0.001,
    )

    return MultipleRunExperiment(run_cfg, data_cfg, model_cfg, train_cfg)


while(True):
    gpn_e = create_experiment("GPN")
    # lop_e = create_experiment("GPN_LOP")
    res = gpn_e.run()

pre
tensor([6, 4, 3,  ..., 1, 2, 3], device='cuda:0')
y val after mask
tensor([4, 2, 1, 1, 1, 1, 2, 1, 3, 2, 4, 4, 1, 4, 1, 1, 3, 3, 1, 4, 1, 0, 1, 1,
        4, 2, 1, 1, 4, 1, 2, 1, 1, 3, 2, 0, 3, 2, 4, 2, 3, 4, 2, 1, 4, 1, 3, 4,
        1, 3, 0, 3, 4, 1, 1, 1, 3, 1, 1, 1, 1, 3, 3, 4, 2, 1, 1, 1, 1, 3, 1, 0,
        2, 0, 1, 4, 4, 4, 2, 1, 1, 4, 4, 2, 2, 4, 1, 1, 4, 3, 3, 3, 0, 4, 2, 4,
        2, 4, 3, 1, 1, 2, 4, 1, 4, 4, 1, 3, 1, 1, 1, 0, 2, 1, 3, 1, 4, 0, 1, 3,
        0, 4, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 3, 1, 3, 3, 1, 1, 3, 4, 2,
        0, 2, 4, 2, 3, 1, 1, 2, 1, 3, 1, 4, 3, 3, 2, 2, 2, 4, 4, 1, 0, 3, 0, 2,
        1, 1, 0, 4, 1, 1, 2, 2, 3, 1, 2, 3, 4, 1, 3, 0, 1, 0, 2, 1, 3, 1, 1, 4,
        1, 4, 1, 3, 3, 2, 3, 1, 1, 1, 3, 4, 4, 1, 4, 1, 2, 1, 1, 2, 1, 1, 3, 2,
        1, 0, 4, 1, 1, 1, 1, 3, 4, 4, 1, 4, 3, 1, 2, 1, 4, 3, 4, 3, 0, 0, 4, 1,
        1, 2, 3, 1, 4, 3, 1, 1, 4, 3, 0, 2, 2, 0, 1, 1, 2, 0, 4, 1, 3, 2, 1, 4,
        1, 3, 3, 3, 3, 1, 4, 1, 1, 1, 4, 3, 4, 1,

IndexError: index 4433714156079041824 is out of bounds for dimension 1 with size 5

In [15]:
res = gpn_e.run()

ValueError: Expected parameter probs (Tensor of shape (647, 5)) of distribution Categorical(probs: torch.Size([647, 5])) to satisfy the constraint Simplex(), but found invalid values:
tensor([[nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        ...,
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan]])

In [5]:
res_lop = lop_e.run()

Epoch 1/5:
 [Elapsed 0:00:05 | 0.18 it/s] REG: 0.17459, UCE: 726.76605, train_CE: 2.74165, train_ECE: 0.19104, train_accuracy: 0.19469, train_average_entropy: 1.22888, train_avg_prediction_confidence_aleatoric: 0.38685, train_avg_prediction_confidence_epistemic: 101.21262, train_avg_sample_confidence_aleatoric: 0.38685, train_avg_sample_confidence_epistemic: 219.37579, train_avg_sample_confidence_epistemic_entropy: 3.58095, train_avg_sample_confidence_features: 261.62350, train_avg_sample_confidence_neighborhood: nan, train_brier_score: 0.98443, train_confidence_aleatoric_apr: 0.14947, train_confidence_aleatoric_auroc: 0.38499, train_confidence_epistemic_apr: 0.14950, train_confidence_epistemic_auroc: 0.38511, train_confidence_structure_apr: nan, train_confidence_structure_auroc: nan, val_CE: 2.73754, val_ECE: 0.21184, val_accuracy: 0.19320, val_average_entropy: 1.22888, val_avg_prediction_confidence_aleatoric: 0.38837, val_avg_prediction_confidence_epistemic: 101.61166, val_avg_sample

In [6]:
import pandas as pd
from gpn.utils.utils import results_dict_to_df

df_lop = results_dict_to_df(res_lop)
df = results_dict_to_df(res)

pd.set_option("display.max_rows", None)
(pd.DataFrame(
    dict(
        val_gpn=df["val"],
        test_gpn=df["test"],
        val_lop=df_lop["val"],
        test_lop=df_lop["test"],
    )
)).round(4).dropna()

val_gpn     test_gpn  \
accuracy                                          0.9212       0.9307   
brier_score                                       0.2756       0.2648   
ECE                                               0.1194       0.1242   
confidence_aleatoric_apr                          0.9888       0.9863   
confidence_epistemic_apr                          0.9841       0.9878   
confidence_aleatoric_auroc                        0.8883       0.8734   
confidence_epistemic_auroc                        0.8496       0.8656   
CE                                                0.3441       0.3233   
avg_prediction_confidence_aleatoric               0.8018       0.8070   
avg_prediction_confidence_epistemic          233354.0156  233844.2812   
avg_sample_confidence_aleatoric                   0.8018       0.8070   
avg_sample_confidence_epistemic              260795.7500  261597.2969   
avg_sample_confidence_epistemic_entropy          28.5516      28.6717   
avg_sample_confidence_features               331778.2500  316633.6875   
average_entropy                                   0.5698       0.5564   
ood_detection_aleatoric_apr                       0.6049       0.6188   
ood_detection_aleatoric_auroc                     0.7616       0.7785   
ood_detection_epistemic_apr                       0.8685       0.8674   
ood_detection_epistemic_auroc                     0.9277       0.9300   
ood_detection_epistemic_entropy_apr               0.6871       0.6905   
ood_detection_epistemic_entropy_auroc             0.8077       0.8013   
ood_detection_features_apr                        0.6855       0.6911   
ood_detection_features_auroc                      0.8033       0.7973   
ood_accuracy                                      0.0000       0.0000   
ood_avg_prediction_confidence_aleatoric           0.6299       0.6247   
ood_avg_prediction_confidence_epistemic       34484.0273   32941.9570   
ood_avg_sample_confidence_aleatoric               0.6299       0.6247   
ood_avg_sample_confidence_epistemic           53130.5000   52436.4375   
ood_avg_sample_confidence_epistemic_entropy      20.8040      21.0837   
ood_avg_sample_confidence_features            38174.3164   29297.6777   
ood_average_entropy                               0.8955       0.9091   
id_accuracy                                       0.9212       0.9307   
id_avg_prediction_confidence_aleatoric            0.8018       0.8070   
id_avg_prediction_confidence_epistemic       233354.0156  233844.2812   
id_avg_sample_confidence_aleatoric                0.8018       0.8070   
id_avg_sample_confidence_epistemic           260795.7500  261597.2969   
id_avg_sample_confidence_epistemic_entropy       28.5516      28.6717   
id_avg_sample_confidence_features            331778.2500  316633.6875   
id_average_entropy                                0.5698       0.5564   

                                                 val_lop     test_lop  
accuracy                                          0.9274       0.9351  
brier_score                                       0.5119       0.5077  
ECE                                               0.3634       0.3645  
confidence_aleatoric_apr                          0.9746       0.9779  
confidence_epistemic_apr                          0.9685       0.9721  
confidence_aleatoric_auroc                        0.7526       0.7725  
confidence_epistemic_auroc                        0.6744       0.6930  
CE                                                0.7138       0.7063  
avg_prediction_confidence_aleatoric               0.5773       0.5844  
avg_prediction_confidence_epistemic           89537.2734   92726.1094  
avg_sample_confidence_aleatoric                   0.5773       0.5844  
avg_sample_confidence_epistemic              105728.5156  108691.8516  
avg_sample_confidence_epistemic_entropy          15.1576      15.2871  
avg_sample_confidence_features               117744.5938  124745.9219  
average_entropy                                 